"""'Add_pdf_url'

Revision ID: a4ce2b0208a4
Revises: b1cc77e95c17
Create Date: 2026-06-18 21:48:22.354450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ce2b0208a4'
down_revision: Union[str, Sequence[str], None] = 'b1cc77e95c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('pdf_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'reports', 'users', ['editor_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['department_head_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['president_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'pdf_url')
    # ### end Alembic commands ###
