"""Add html_content to Report

Revision ID: daf0b6063cdb
Revises: 0ad94f6c2109
Create Date: 2026-06-14 15:36:29.826152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'daf0b6063cdb'
down_revision: Union[str, Sequence[str], None] = '0ad94f6c2109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # op.drop_index(op.f('ix_settings_id'), table_name='settings')
    # op.drop_index(op.f('ix_settings_key'), table_name='settings')
    # op.drop_table('settings')
    op.add_column('reports', sa.Column('html_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'html_content')
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('value', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=1)
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###
