"""add visit requests table

Revision ID: de590194aeca
Revises: c1fc6c19fcf8
Create Date: 2026-06-14 18:21:37.309940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de590194aeca'
down_revision: Union[str, Sequence[str], None] = 'c1fc6c19fcf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('female_students', sa.Integer(), nullable=True),
    sa.Column('need_guide', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_requests_id'), 'visit_requests', ['id'], unique=False)
    op.create_index(op.f('ix_visit_requests_school_name'), 'visit_requests', ['school_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_requests_school_name'), table_name='visit_requests')
    op.drop_index(op.f('ix_visit_requests_id'), table_name='visit_requests')
    op.drop_table('visit_requests')
    # ### end Alembic commands ###
